### ISSUE TITLE
hg19util module not found

### ISSUE THREAD

**Issue by dnygard** [namphuon/ViFi#1]
Hi,
When trying to run for the first time after installing all dependencies in the README, I got an error that the hg19util module could not be found. The only reference to a python module with this name on google is one in AmpliconArchitect. You reference AmpliconArchitect in the ViFi paper but it is not listed as a dependency. Is this a dependency that has gone unlisted or does the hg19util module come from somewhere else?

**Comment by namphuon** [comment]
Sorry, the hg19util mode is in the python module of ViFi.  I updated the README with an additional step to include this folder in the PYTHONPATH.  I will create a setup.py script, though, that will take care of these issues to make installation more easy in the future.
