### ISSUE TITLE
ViFi can be used for non-human genome and virus??

### ISSUE THREAD

**Issue by ssri28** [namphuon/ViFi#13]
Dear ViFi Team

I have a Viral infected Fish sequence. I would like to try running ViFi for my Data.
I have both Reference Genome and Viral sequence.
is it possible for me to use ViFi and Identify the Fusion genes from Virus and Fish Genome?

Kind Regards
Sri

**Comment by namphuon** [comment]
I apologize for very long delay.  I have updated ViFi to be completely dockerized and have included new pipelines for analyzing/building your own reference dataset.  ViFi can be run on the fish data, and instructions on how to do so are listed in the new TUTORIAL.MD file.  Let me know if there's any problems.
