### ISSUE TITLE
Would ViFi remove duplicate reads?

### ISSUE THREAD

**Issue by ouzhihua** [namphuon/ViFi#15]
Hi, 

I would like to know whether ViFi would remove duplicate reads before determining the integration sites. if so, in which step would ViFi conduct deduplication? 

Thanks in advance.

Gina

**Comment by namphuon** [comment]
ViFi does not remove duplicate reads before running, instead it uses whatever data it sees available.  I will see if future versions adds some data cleaning to check for duplicate reads, but that current feature is not implemented.
