### ISSUE TITLE
404 not found for google driver link

### ISSUE THREAD

**Issue by zhang616123** [namphuon/ViFi#28]
Hi，
I noted this url: https://drive.google.com/open?id=0ByYcg0axX7udUDRxcTdZZkg0X1k look like not a valid url now (404 not found), could you please update it.
Thanks for yur reading.
Best.
Zhang

**Comment by alexjacobsCDS** [comment]
Hi Zhang (or anyone else looking here later),
Checkout this fork of the repo by @sara-javadzadeh https://github.com/sara-javadzadeh/ViFi
In `setup_linux_mac.sh` there is a google drive link to the data that is working at the moment at least in 

The startup scripts in that repo are also very helpful

**Comment by zhang616123** [comment]
> 
> 
> Hi Zhang (or anyone else looking here later),
> Checkout this fork of the repo by @sara-javadzadeh https://github.com/sara-javadzadeh/ViFi
> In `setup_linux_mac.sh` there is a google drive link to the data that is working at the moment at least in
> 
> The startup scripts in that repo are also very helpful

Hi, lexjacobsCDS.
Thanks for your quick reponse, sorry for any delay. I think it will work well.
Best.
Zhang.
