### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by breez1** [namphuon/ViFi#3]
Hello!
May I ask for a help?
I am not sure what is the problem and I can not find pysam/libcalignmentfile.pyx, and I can only find a file called libcalignmentfile.pxd. I used the hmm files and test fa files provide by ViFi. I finished running HMMS. Could you please tell me how to deal with the following error?

[Finished running HMMS]: 6897.991433
[Cluster and identify integration points]: 6897.991463

Traceback (most recent call last):
  File "/home/brz/wsy/vifi/ViFi/scripts/merge_viral_reads.py", line 118, in <module>
    outputFile.header['SQ'] = references
  File "pysam/libcalignmentfile.pyx", line 537, in pysam.libcalignmentfile.AlignmentHeader.__setitem__
TypeError: AlignmentHeader does not support item assignment (use header.to_dict()

Usage:   samtools sort [options] <in.bam> <out.prefix>

**Comment by namphuon** [comment]
It might be an issue with your version of pysam/samtools.  Can you send me which version of pysam you're using/samtools you're using?

**Comment by namphuon** [comment]
This issue was caused by conflicts between Samtools versions.  To deal with this issue, I have depreciated the command line version of ViFi and instead, recommend using the Docker image, which fixes all conflicts between the versions of software.

**Comment by pintoa1-mskcc** [comment]
If we cannot use the docker image, as the docker is not installed and cannot be installed, how would you recommend using the new version of ViFi?

I have edited the pysam confilict and the command line version works fine. Are there any specific difference between the two?
