### ISSUE TITLE
reduced.csv not being created

### ISSUE THREAD

**Issue by dnygard** [namphuon/ViFi#4]
Hello,
When running my cases I am continually getting an empty table for output. I am faced with the following error: 

"Traceback (most recent call last):
  File "/home/dnygard/ViFi/scripts/merge_viral_reads.py", line 116, in <module>
    scores = read_scores_file(args.reducedName[0])
  File "/home/dnygard/ViFi/scripts/merge_viral_reads.py", line 19, in read_scores_file
    input = open(hmm_file, 'r')  
IOError: [Errno 2] No such file or directory: 'tmp/temp/reduced.csv'
0"

I am wondering in what step is tmp/temp/reduced.csv produced so I might be able to trace the source of this error. If you have any suggestions they would be much appreciated. Thank you.

**Comment by namphuon** [comment]
The reduced.csv file would be created during the HMMER search of the sequences.  Could email me (namphuon@cs.utah.edu) the files created by ViFi and the command you used and a output of the run and I can try to help you track it down?
