### ISSUE TITLE
Error;  hg19util

### ISSUE THREAD

**Issue by autobot101** [namphuon/ViFi#6]
Hello,
I am trying to run vifi, but everytime I am getting this error.

**Traceback (most recent call last):
  File "run_vifi.py", line 4, in <module>
    import hg19util as hg19
ImportError: No module named hg19util**

Kindly help me with this error.

Thanks
AKS

**Comment by Anuragksingh** [comment]
Duplicate of #1

**Comment by autobot101** [comment]
Duplicate of #1 
Error sorted out
Thanks
